--- #YAML:1.0
name: Class-DBI-LazyInflate
version: 0.02
author:
  - Daisuke Maki E<lt>dmaki@cpan.orgE<gt>
abstract: Defer Inflating Of Columns Until They Are Used
license: perl
requires:
  Class::DBI: 0
  Data::Lazy: 0
provides:
  Class::DBI::LazyInflate:
    file: lib/Class/DBI/LazyInflate.pm
    version: 0.02
generated_by: Module::Build version 0.2607
